FROM node:18.14.0
WORKDIR /app
COPY package*.json ./
COPY ./package-lock.json ./
RUN npm install
COPY . .
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh
CMD ["npm", "run", "dev"]