FROM node:18.14.0
WORKDIR /app
COPY package*.json ./
COPY ./package-lock.json ./
RUN npm install
COPY . .

COPY --from=itqa47/frontend:latest /app/dist /app/public
CMD ["node", "server.js"]
EXPOSE 3000